Presentation/Controllers/RHController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entity;
using System.Net.Http;
using System.Net;
using System.IO;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Twilio.AspNet.Mvc;
using Twilio;
using Twilio.TwiML;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;
using System.Configuration;

namespace Presentation.Controllers
{
    public class RHController : Controller
    {
        public static humanressources currentrh;
        // GET: RH
        public static humanressources hr = new humanressources
        { email = "advteam@esprit.tn",
            password = "123"
        };

        public ActionResult RHlogin(humanressources hr)
        { if (!ModelState.IsValid)
            {
                return View();
            }

            else
            {

                var request = (HttpWebRequest)WebRequest.Create("http://localhost:9080/ProjetPidevJee-web/rest/Employee/LogHr/" + hr.email + hr.password);

                request.Method = "GET";

                request.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

                var content = string.Empty;
                try
                {

                    var xRES = (HttpWebResponse)request.GetResponse();
                    using (var response = (HttpWebResponse)request.GetResponse())
                    {
                        using (var stream = response.GetResponseStream())
                        {
                            using (var sr = new StreamReader(stream))
                            {
                                content = sr.ReadToEnd();
                            }
                        }
                    }


                    if (content == null)
                    {

                        return View();

                    }
                    else
                    { return RedirectToAction("PrintEmp", "Employee");
                        try
                        {
                            JObject json = JObject.Parse(content);


                            var result = JsonConvert.DeserializeObject<humanressources>(content);
                            currentrh = result;




                            Session["RHSessionData1"] = currentrh;




                            //              return RedirectToAction("PrintEmp", "Employee");

                            return RedirectToAction("PrintEmp", "Employee");



                        }
                        catch (Exception ex)
                        {


                            return View();
                        }
                    }
                }
                catch (WebException ex)
                {

                    return View();
                }


            }




        }

        // GET: RH/Details/5
        public ActionResult PasswordForget()
        {
            return View();
           

        }

        // GET: RH/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RH/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RH/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RH/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RH/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RH/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
} 

Presentation/Controllers/SmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Twilio.AspNet.Mvc;
using Twilio;
using Twilio.TwiML;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;
using System.Configuration;
namespace sendsmsandrecieve.Controllers
{
    public class SmsController : TwilioController
    {
        public ActionResult sendSms()
        {
            var accountSid = "ACc0011081df783be26ed0e51c25f15564";
            var authToken = "d3627c4f6c940b375a39a27a4a7602ac";
            TwilioClient.Init(accountSid, authToken);
            var to = new PhoneNumber("+21622326677");
            var from = new PhoneNumber("+15129942395");
            try
            {
                var message = MessageResource.Create(
                body: "your password is: 123",
                from: from,
                to: to);
            }
            catch(Twilio.Exceptions.ApiException e)
            {

            }
           return RedirectToAction("RHlogin", "RH");
        }
    }
}

Presentation/Views/RH/Create.cshtml
@model Domain.Entity.humanressources

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Home/Index.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V20</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Content/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/main.css">
    <!--===============================================================================================-->
</head>
<body>
    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>humanressources</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Fname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Fname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Lname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.country, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.country, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.country, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.experience, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.experience, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.experience, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.telephone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.telephone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.telephone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Presentation/Views/RH/PasswordForget.cshtml
<html>
<body>
    <h2>PasswordForget</h2>
    enter your email :
    <input type="email" />
<input type="button" class="btn btn-info" value="Recover Password" onclick="location.href='@Url.Action("sendSms", "Sms")'" />
</body>
</html>

Presentation/Views/RH/RHlogin.cshtml
@model Domain.Entity.humanressources
@{
    ViewBag.Title = "RHlogin";
    Layout = null;
}



<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V20</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Content/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/main.css">
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-b-160 p-t-50">
                <span class="login100-form-title p-b-43">
                    Hello<br />
                
                    Mr Human Ressources
                </span>
                <h4 style="color:white;">Please enter your information To continue</h4>
                <br />
                <form class="login100-form validate-form" action="" method="post">
                        
   <div class="wrap-input100 rs1 validate-input" data-validate="Username is required">
       @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "input100" ,Name = "username" } })
   
         
           <span class="label-input100">email</span>
                    </div>


                    <div class="wrap-input100 rs2 validate-input" data-validate="Password is required">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "input100" ,Name= "pass" } })
                     
                     
                        <span class="label-input100">Password</span>
                    </div>

                    <div class="container-login100-form-btn">
                        <button type="submit" class="login100-form-btn"  onclick="location.href='@Url.Action("PrintEmp", "Employee")'" />
                            Sign in
                        </button>
                    </div>

                    <div class="text-center w-full p-t-23">
                        
                     
                       
                       
                    </div>
                </form>
                <input type="button" class="btn btn-info" value="Forget Password?" onclick="location.href='@Url.Action("PasswordForget", "RH")'" />
            </div>
        </div>
    </div>




   
    <!--===============================================================================================-->
    <script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>

</body>
</html>