Presentation/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Controllers
{
    public class ChatController : Controller
    {
        // GET: Chat
        public ActionResult Index()
        {
            return View();
        }

        // GET: Chat/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Chat/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Chat/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Chat/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Chat/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Chat/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Chat/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Presentation/Controllers/DayOffController.cs
using Domain.Entity;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Controllers
{
    public class DayOffController : Controller
    {
        IDayOffService ds;
        public DayOffController()
        {
            ds = new DayOffService();
        }
        // GET: DayOff
        public ActionResult Index()
        {
            return View(ds.GetMany());
        }
        public ActionResult publication()
        {
            return View();
        }
        // GET: DayOff/Details/5
        public ActionResult Details(int id)
        {
            dayoff c = ds.GetById(id);
            if (c == null)
            {

                return HttpNotFound();

            }

            return View(c);
        }

        // GET: DayOff/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DayOff/Create
        [HttpPost]
        public ActionResult Create(dayoff day)
        {
               ds.Add(day);
            ds.Commit();
            //  return RedirectToAction("index");
            return RedirectToAction("Index");
        }

        // GET: DayOff/Edit/5
        public ActionResult Edit(int id)
        {

            dayoff c = ds.GetById(id);

            if (c == null)
            {
                return HttpNotFound();
            }
            return View(c);
        }

        // POST: DayOff/Edit/5
        [HttpPost]
        public ActionResult Edit(dayoff day)
        {
            dayoff c1 = ds.GetById(day.id);
            c1.nbjrs = day.nbjrs;

            if (ModelState.IsValid)
            {
                ds.Update(c1);
                ds.Commit();

                return RedirectToAction("Index");

            }

            return RedirectToAction("Index");
        }

        // GET: DayOff/Delete/5
        public ActionResult Delete(int id)
        {
            return View(ds.GetById(id));
        }

        // POST: DayOff/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, dayoff day)
        {
            day = ds.GetById(id);
            ds.Delete(day);
            ds.Commit();
            return RedirectToAction("Index");
        }
        //public ActionResult Pdf()
        //{
        //    return new ActionAsPdf("Index")
        //    {
        //        FileName = Server.MapPath("~/Content/CRM.Pdf")

        //    };
        //}
    }
}

Presentation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Chat()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Presentation/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Presentation/Views/Home/Chat.cshtml
<style>
    div.panel-body {
        overflow: scroll;
        background: url('http://subtlepatterns.com/patterns/geometry2.png');
    }
</style>
<h2>ChatBox</h2>
<div class="chat-panel panel panel-default">
    <div class="panel-heading">
        ChatBox using SingalR
        <i class="fa fa-paper-plane fa-fw"></i>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body" id="chat" style="height:250px;">
        <input type="hidden" id="displayname" />

        <p id="discussion"></p>
    </div>
    <!-- /.panel-body -->
    <div class="panel-footer">
        <div class="input-group">
            <input id="message" type="text" name="message" class="form-control input-sm" placeholder="Type your message here..." />

            <span class="input-group-btn">
                <input type="button" class="btn btn-warning btn-sm" id="sendmessage" value="Send">

            </span>
        </div>
    </div>
    <a href="@Url.Action("allPub","Publication")"> <h1 >Go Back</h1></a>
</div>
<script src="~/Content/js/core/jquery.min.js"></script>
<!--Script references. -->
<!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
<!--Reference the SignalR library. -->
<script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
<!--Reference the autogenerated SignalR hub script. -->
<script src="~/signalr/hubs"></script>
<!--SignalR script to update the chat page and send messages.-->
<script>
        $(function () {
         //   alert('hello!!');
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessageToPage = function (name, message) {
                if (name == "Atir") {
                    // Add the message to the page.
                    $('#discussion').append('<p style="color:green; text-align:left; width:500px"><strong><img = src="https://www.phplivesupport.com/pics/icons/avatars/public/avatar_7.png" title="Atir">'
                        + ' </strong> ' + htmlEncode(message) + '</p>');
                }
                else if (name != "Atir") {
                    // Add the message to the page.
                    $('#discussion').append('<p style="color:blue;text-align:right;"><strong><img = src="https://www.phplivesupport.com/pics/icons/avatars/public/avatar_71.png" title="Peter">'
                        + ' </strong> ' + htmlEncode(message) + '</p>');
                }
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
</script>

Presentation/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Presentation/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/Content/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/Content/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        Paper Dashboard 2 by Creative Tim
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <!-- CSS Files -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="@Url.Content("~/Content/js/jquery-ui.min.css")" rel="stylesheet" />
    <!-- Begin emoji-picker Stylesheets -->
    <link href="~/Content/smiley/css/emoji.css" rel="stylesheet">
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/paper-dashboard.css?v=2.0.0" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="~/Content/demo/demo.css" rel="stylesheet" />
    <style>#xD{
    width:900x;

}</style>
    <link href="~/Content/css/mystyle.css"  rel="stylesheet"/>
</head>

<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="white" data-active-color="danger">
            <!--
                Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
            -->
            <div class="logo">
                <a href="https://www.advyteam.com" class="simple-text logo-mini">
                    <div class="logo-image-small">
                        <img src="~/Content/img/logo-small.png">
                    </div>
                </a>
                <a href="https://www.advyteam.com" class="simple-text logo-normal">
                   Advy Team
                    <!-- <div class="logo-image-big">
                      <img src="../assets/img/logo-big.png">
                    </div> -->
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="active ">
                        <a href="@Url.Action("allPub","Publication")">
                            <i class="nc-icon nc-bank"></i>
                            <p>My Acceuil</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Create", "DayOff")">
                            <i class="nc-icon nc-diamond"></i>
                            <p>DayOff Demand</p>
                        </a>
                    </li>
                   
                    <li>
                        <a href="@Url.Action("Chat", "Home")">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>ChatRoom</p>
                        </a>
                    </li>
                    
                  
                    <li class="active-pro">
                        <a href="@Url.Action("Login", "Login")">
                            <i class="nc-icon nc-spaceship"></i>
                            <p>Disconnect</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-toggle">
                            <button type="button" class="navbar-toggler">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>

                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <form>
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Search...">
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <i class="nc-icon nc-zoom-split"></i>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link btn-magnify" href="#pablo">
                                    <i class="nc-icon nc-layout-11"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Stats</span>
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item btn-rotate dropdown">
                                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="nc-icon nc-bell-55"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Some Actions</span>
                                    </p>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link btn-rotate" href="#pablo">
                                    <i class="nc-icon nc-settings-gear-65"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Account</span>
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <!-- <div class="panel-header panel-header-lg">

              <canvas id="bigDashboardChart"></canvas>


            </div> -->
            

            <div class="content">
              
             @RenderBody()
            </div>
           
        </div>
    </div>
    <!--   Core JS Files   -->
    
    <script src="~/Content/js/core/bootstrap.min.js"></script>
    <script src="~/Content/js/core/jquery.min.js"></script>
    <script src="@Url.Content("~/Content/js/jquery-ui.min.js")"></script>
    <script src="~/Content/smiley/js/config.js"></script>
    <script src="~/Content/smiley/js/util.js"></script>
    <script src="~/Content/smiley/js/jquery.emojiarea.js"></script>
    <script src="~/Content/smiley/js/emoji-picker.js"></script>
    <script src="~/Content/js/core/popper.min.js"></script>
    <script src="~/Content/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <!--  Google Maps Plugin    -->
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
    <!-- Chart JS -->
   
    <script src="~/Content/js/plugins/chartjs.min.js"></script>
    
    <!--  Notifications Plugin    -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script src="~/Content/js/plugins/bootstrap-notify.js"></script>
    <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/Content/js/paper-dashboard.min.js?v=2.0.0" type="text/javascript"></script>
    <!-- Paper Dashboard DEMO methods, don't include it in your project! -->
    <script src="~/Content/demo/demo.js"></script>
    <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/assets-for-demo/js/demo.js
      demo.initChartsPages();
    });
    </script>
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable({

                "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
                "iDisplayLength": 5,

            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            // This will make every element with the class "date-picker" into a DatePicker element
            $('.date-picker').datepicker();
            
        })
    </script>   
    <script>
      $(function() {
        // Initializes and creates emoji set from sprite sheet
        window.emojiPicker = new EmojiPicker({
          emojiable_selector: '[data-emojiable=true]',
          assetsPath: '../../Content/smiley/img/',
          popupButtonClasses: 'fa fa-smile-o'
        });
        // Finds all elements with `emojiable_selector` and converts them to rich emoji input fields
        // You may want to delay this step if you have dynamically created input fields that appear later in the loading process
        // It can be called as many times as necessary; previously converted input fields will not be converted again
        window.emojiPicker.discover();
      });
    </script>

</body>

</html>